export enum SocketStateTypes {
  NEW_MISSION = 10,
  MISSION_INFO_CHANGED = 11,
  VOLUNTEER_LOCATION_CHANGED = 12,
  VOLUNTEER_OFFLINE = 13,
  MISSION_TIMEOUT = 14,
  VOLUNTEER_JOIN_MISSION = 15,
  VOLUNTEER_QUIT_MISSION = 16,
  FACE_PASS = 17,
  MISSION_COMPLETED = 18,
  MISSION_CANCELED = 19,
}
